// <copyright file="DequeTest.DequeEnumeration.g.cs" company="Authorized User">Copyright © Authorized User 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PurelyFunctional.Test
{
	public partial class DequeTest
	{
[TestMethod]
[PexGeneratedBy(typeof(DequeTest))]
public void DequeEnumeration563()
{
    int[] ints = new int[6];
    ints[1] = 264;
    ints[2] = 272;
    ints[3] = 320;
    ints[4] = 256;
    ints[5] = 257;
    this.DequeEnumeration<int>(ints);
}
	}
}
