// <copyright file="ListTest.NSListTail.g.cs" company="Authorized User">Copyright © Authorized User 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

namespace PurelyFunctional.Test
{
	public partial class ListTest
	{
[TestMethod]
[PexGeneratedBy(typeof(ListTest))]
public void NSListTail286()
{
    int[] ints = new int[3];
    ints[0] = 128;
    ints[2] = 1;
    this.NSListTail<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ListTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void NSListTailThrowsPexAssertFailedException932()
{
    int[] ints = new int[4];
    ints[0] = 257;
    ints[1] = 258;
    ints[2] = 2;
    ints[3] = 3;
    this.NSListTail<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ListTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void NSListTailThrowsPexAssertFailedException57()
{
    int[] ints = new int[5];
    ints[1] = 129;
    ints[2] = 8;
    ints[3] = 64;
    ints[4] = 1;
    this.NSListTail<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ListTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void NSListTailThrowsPexAssertFailedException607()
{
    int[] ints = new int[6];
    ints[0] = 2;
    ints[1] = 131;
    ints[2] = 3;
    ints[3] = 4;
    ints[5] = 1;
    this.NSListTail<int>(ints);
}
	}
}
